### ISSUE TITLE
Swipe the tabitem will reboot the phone。

### ISSUE THREAD

**Issue by tianjyan** [JustinXinLiu/Continuity#1]
My phone will reboot when I swipe the tabitem and my phone is lumia 930.

**Comment by JustinXinLiu** [comment]
This is actually a [bug](https://github.com/Microsoft/composition/issues/19) in the Windows Composition API, which, will be fixed in the next insider build.

**Comment by tianjyan** [comment]
That helps a lot. Thank you.
