### ISSUE TITLE
Building for 14393

### ISSUE THREAD

**Issue by 10Dev** [JustinXinLiu/Continuity#3]
FWIW (if people wander by before Justin updates the project)

Here is how to get a 14393 Build:
1. Download the project and copy the Continuity sub-dir into your solution
2. edit csproj to change to 14393 and remove SDK refs near end
3. Use Nuget to update the references remaining after: removing the RX-Xaml and RX-Main, add System.Reactive, System.Reactive.WindowsRuntime, System.Reactive.Windows.Threading
4. Robmikh has changed to Robmikh.CompositionSurfaceFactory but I didn't take the time to figure out the changes so I removed the Starfield stuff from the project for now.
5. Set your project to Min: 14393, Target: 14393

I have tested the Tab control on 14393 and it works. Thanks for the project Justin.

**Comment by JustinXinLiu** [comment]
Hey thanks! I will update this repo hopefully by this weekend.

**Comment by JustinXinLiu** [comment]
Updated to be compatible with _10586_ and _14393_.
