### ISSUE TITLE
BackdropTintBlurBrush does not accept Custom Color

### ISSUE THREAD

**Issue by jasonwurzel** [JustinXinLiu/Continuity#5]
Hi, I'm using this simple construct where I set the BackdropTintBlurBrush as Background of a ListView. All works well if I use some given Color like "White":
```
<views:BackdropTintBlurBrush x:Key="BackdropTintBlurBrush" 
BlurAmount="12" TintColor="White" FallbackColor="Black" />
```
But if I use some custom color, the Background is just displayed Black:
```
<views:BackdropTintBlurBrush x:Key="BackdropTintBlurBrush" 
BlurAmount="12" TintColor="#384F60" FallbackColor="#384F60" />
```

I debugged into the implementation, but there seem to be no Issue in the OnConnected method.

**Comment by JustinXinLiu** [comment]
Hey sorry for the late reply.

What if you change the `Mode` from `LinearBurn` to `SoftLight`?

**Comment by jasonwurzel** [comment]
Hi, 

no problem! I totally forgot about this issue. In the end, I just didn't see the difference between the very dark brush and the dark background. placing the ListView in front of some really high contrast background showed that it worked as expected, just very dark. 
As you proposed, changing the Mode to something else helped in my case.
